using System;
using System.Reflection;
using System.Resources;
using System.Security.Permissions;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("2.0.0.5")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0.5")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyProductAttribute("Net.Kniaz.AHP.dll")]
[assembly: AssemblyDescriptionAttribute("Version: [2.0.0.5] Framework: [net-2.0]Machine: [SEALION]  Built: [01/21/2008 11:" +
    "26:25] Creator: kkniaz Comments: ")]
[assembly: AssemblyCultureAttribute("")]
[assembly: NeutralResourcesLanguageAttribute("")]
[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: SecurityPermissionAttribute(SecurityAction.RequestMinimum, Execution=true, Assertion=true)]

