using System;
using System.Reflection;
using System.Resources;
using System.Security.Permissions;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("3.5.0.0")]
[assembly: AssemblyInformationalVersionAttribute("3.5.0.0")]
[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyProductAttribute("GeneralMatrix.dll")]
[assembly: AssemblyDescriptionAttribute("Version: [3.5.0.0] Framework: [net-3.5]Machine: [WALRUSVM]  Built: [10/02/2009 22" +
    ":33:48] Creator: kkniaz Comments: ")]
[assembly: AssemblyCultureAttribute("")]
[assembly: NeutralResourcesLanguageAttribute("")]
[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(false)]
[assembly: SecurityPermissionAttribute(SecurityAction.RequestMinimum, Execution=true, Assertion=true)]

